# Generated by Django 4.1.5 on 2023-01-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('score', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to='cardgame.card')),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_attack', to='cardgame.attack')),
                ('num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defense_num', to='cardgame.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('큰 수', '큰 수'), ('작은 수', '작은 수')], max_length=30)),
                ('status', models.CharField(choices=[('끝', '끝'), ('진행 중', '진행 중')], max_length=30)),
                ('attack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardgame_attack', to='cardgame.attack')),
                ('defense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardgame_defense', to='cardgame.defense')),
                ('win_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardgame_user', to='cardgame.user')),
            ],
        ),
        migrations.AddField(
            model_name='attack',
            name='attack_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_user_user', to='cardgame.user'),
        ),
        migrations.AddField(
            model_name='attack',
            name='attacked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacked_user_user', to='cardgame.user'),
        ),
        migrations.AddField(
            model_name='attack',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_card', to='cardgame.card'),
        ),
    ]
