# Generated by Django 4.1.5 on 2023-01-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_user', models.CharField(max_length=64)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_user', models.CharField(max_length=64)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('큰 수', '큰 수'), ('작은 수', '작은 수')], max_length=30)),
                ('status', models.CharField(choices=[('끝', '끝'), ('진행 중', '진행 중')], max_length=30)),
                ('attack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardgame_attack', to='cardgame.attack')),
                ('defense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardgame_defense', to='cardgame.defense')),
                ('win_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardgame_user', to='cardgame.user')),
            ],
        ),
    ]
