# Generated by Django 4.1.5 on 2023-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgame',
            name='mode',
            field=models.CharField(choices=[('작은 수', '작은 수'), ('큰 수', '큰 수')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cardgame',
            name='status',
            field=models.CharField(choices=[('진행 중', '진행 중'), ('끝', '끝')], max_length=30),
        ),
    ]
